name: whatsapp_media_editor
description: A Flutter application for video editing, GIF conversion and WhatsApp sticker creation
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  image_picker: ^1.0.4
  video_player: ^2.7.1
  video_trimmer: ^2.1.0
  provider: ^6.0.5
  permission_handler: ^10.4.3
  path_provider: ^2.1.1
  share_plus: ^7.1.0
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/